### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Bernardoow** [werner/diyalog#1]
If at init I set style = Animation.style [].

After first modal, the settings of animation come back to default.

**Comment by werner** [comment]
Hi, thanks for checking it out, style is not supposed to be editable, :), but I'll do my best to fix this.

**Comment by Bernardoow** [comment]
Hi werner,

If u need some help. I'm begginer on elm.. 

I tried think how fixed it. U know when it finalize the show of modal? If know save on aux variable the start settings and set back.

**Comment by werner** [comment]
Hi Bernardoow,

I'm a beginner on Elm as well, :), however I think I just come out a solution, it's in the materialize example, in the update function you just have to set the style field for the OkModal and CloseModal pattern matching types like this:

https://github.com/werner/diyalog/blob/master/examples/Materialize.elm#L36
https://github.com/werner/diyalog/blob/master/examples/Materialize.elm#L41

Let me know if you're still having problems.

Best regards.
